// Base de datos de 50 especies de Costa Rica
// Imágenes: Special:FilePath de Wikimedia Commons (resuelve el hash automáticamente)
const animales = [
    {
        id: 1,
        nombreEspanol: "Jaguar",
        nombreIngles: "Jaguar",
        cientificoEspanol: "Panthera onca",
        cientificoIngles: "Panthera onca",
        categoria: "Mamíferos",
        descripcionEspanol: "El felino más grande de América y un símbolo de poder. Habita en selvas densas y áreas protegidas de Costa Rica.",
        descripcionIngles: "The largest feline in the Americas and a symbol of power. It inhabits dense jungles and protected areas of Costa Rica.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Standing_jaguar.jpg?width=600"
    },
    {
        id: 2,
        nombreEspanol: "Tucán pico iris",
        nombreIngles: "Keel-billed toucan",
        cientificoEspanol: "Ramphastos sulfuratus",
        cientificoIngles: "Ramphastos sulfuratus",
        categoria: "Aves",
        descripcionEspanol: "Es notable por su gran pico de colores vivos. Se alimenta principalmente de frutas y vive en las copas de los árboles.",
        descripcionIngles: "Notable for its large, vividly colored beak. It feeds mainly on fruits and lives in the forest canopy.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Keel-billed_toucan.jpg?width=600"
    },
    {
        id: 3,
        nombreEspanol: "Rana calzonuda",
        nombreIngles: "Red-eyed tree frog",
        cientificoEspanol: "Agalychnis callidryas",
        cientificoIngles: "Agalychnis callidryas",
        categoria: "Anfibios",
        descripcionEspanol: "Famosa por sus enormes ojos rojos y costados azules. Es un ícono mundial de la biodiversidad de los bosques tropicales.",
        descripcionIngles: "Famous for its huge red eyes and blue sides. It is a global icon of tropical forest biodiversity.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Agalychnis_callidryas.jpg?width=600"
    },
    {
        id: 4,
        nombreEspanol: "Cocodrilo americano",
        nombreIngles: "American crocodile",
        cientificoEspanol: "Crocodylus acutus",
        cientificoIngles: "Crocodylus acutus",
        categoria: "Reptiles",
        descripcionEspanol: "Gran reptil acuático que habita en ríos, estuarios y manglares, muy común de observar en zonas como el Río Tárcoles.",
        descripcionIngles: "A large aquatic reptile found in rivers, estuaries, and mangroves, commonly spotted near the Tárcoles River.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Crocodylus_acutus.jpg?width=600"
    },
    {
        id: 5,
        nombreEspanol: "Perezoso de tres dedos",
        nombreIngles: "Brown-throated sloth",
        cientificoEspanol: "Bradypus variegatus",
        cientificoIngles: "Bradypus variegatus",
        categoria: "Mamíferos",
        descripcionEspanol: "Famoso por su lentitud, pasa casi toda su vida en las copas de los árboles alimentándose de hojas de Cecropia (Guarumo).",
        descripcionIngles: "Famous for its slowness, it spends nearly its entire life in the treetops feeding on leaves of the Cecropia (guarumo) tree.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Bradypus.jpg?width=600"
    },
    {
        id: 6,
        nombreEspanol: "Lapa roja",
        nombreIngles: "Scarlet macaw",
        cientificoEspanol: "Ara macao",
        cientificoIngles: "Ara macao",
        categoria: "Aves",
        descripcionEspanol: "Ave grande y colorida que destaca por su plumaje rojo, amarillo y azul. Es común verlas volar en parejas en el Pacífico Central.",
        descripcionIngles: "A large, colorful bird known for its red, yellow, and blue plumage. Often seen flying in pairs along the Central Pacific coast.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Scarlet_Macaw.jpg?width=600"
    },
    {
        id: 7,
        nombreEspanol: "Mono congo",
        nombreIngles: "Mantled howler monkey",
        cientificoEspanol: "Alouatta palliata",
        cientificoIngles: "Alouatta palliata",
        categoria: "Mamíferos",
        descripcionEspanol: "Conocido por sus potentes e imponentes aullidos que pueden escucharse a kilómetros de distancia en el bosque tropical.",
        descripcionIngles: "Known for its powerful, resounding howls that can be heard for kilometers through the tropical forest.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Alouatta_palliata.jpg?width=600"
    },
    {
        id: 8,
        nombreEspanol: "Quetzal resplandeciente",
        nombreIngles: "Resplendent quetzal",
        cientificoEspanol: "Pharomachrus mocinno",
        cientificoIngles: "Pharomachrus mocinno",
        categoria: "Aves",
        descripcionEspanol: "Ave sagrada de plumaje verde iridiscente y pecho rojo. Habita en los bosques nubosos de altura, como el de Monteverde.",
        descripcionIngles: "A sacred bird with iridescent green plumage and a red chest. It inhabits high cloud forests such as Monteverde.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Resplendent_Quetzal.jpg?width=600"
    },
    {
        id: 9,
        nombreEspanol: "Rana dardo venenosa",
        nombreIngles: "Strawberry poison-dart frog",
        cientificoEspanol: "Oophaga pumilio",
        cientificoIngles: "Oophaga pumilio",
        categoria: "Anfibios",
        descripcionEspanol: "Pequeña rana de color rojo brillante con patas azules, apodada popularmente como 'Blue Jeans'. Su piel posee toxinas defensivas.",
        descripcionIngles: "A small, bright-red frog with blue legs, popularly nicknamed 'Blue Jeans'. Its skin contains defensive toxins.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Oophaga_pumilio.jpg?width=600"
    },
    {
        id: 10,
        nombreEspanol: "Garrobo / Iguana negra",
        nombreIngles: "Black spiny-tailed iguana",
        cientificoEspanol: "Ctenosaura similis",
        cientificoIngles: "Ctenosaura similis",
        categoria: "Reptiles",
        descripcionEspanol: "Uno de los lagartos más rápidos del mundo. Es terrestre y se le ve frecuentemente tomando el sol sobre rocas o troncos.",
        descripcionIngles: "One of the fastest lizards in the world. It is terrestrial and often seen basking in the sun on rocks or logs.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Ctenosaura_similis.jpg?width=600"
    },
    {
        id: 11,
        nombreEspanol: "Danta / Tapir",
        nombreIngles: "Baird's tapir",
        cientificoEspanol: "Tapirus bairdii",
        cientificoIngles: "Tapirus bairdii",
        categoria: "Mamíferos",
        descripcionEspanol: "El mamífero terrestre más grande de Costa Rica. Excelente nadador, habita en bosques húmedos como el Parque Nacional Corcovado.",
        descripcionIngles: "The largest terrestrial mammal in Costa Rica. An excellent swimmer found in humid forests like Corcovado National Park.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Tapirus_bairdii.jpg?width=600"
    },
    {
        id: 12,
        nombreEspanol: "Colibrí rutilante",
        nombreIngles: "Violet-sabrewing",
        cientificoEspanol: "Campylopterus hemileucurus",
        cientificoIngles: "Campylopterus hemileucurus",
        categoria: "Aves",
        descripcionEspanol: "Uno de los colibríes más grandes de Costa Rica. Los machos tienen un plumaje violeta profundo sumamente llamativo.",
        descripcionIngles: "One of the largest hummingbirds in Costa Rica. Males display a striking, deep violet plumage.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Violet_Sabrewing.jpg?width=600"
    },
    {
        id: 13,
        nombreEspanol: "Pizote / Coatí",
        nombreIngles: "White-nosed coati",
        cientificoEspanol: "Nasua narica",
        cientificoIngles: "Nasua narica",
        categoria: "Mamíferos",
        descripcionEspanol: "Pariente de los mapaches, se caracteriza por su cola larga y hocico flexible. Suelen andar en grupos ruidosos.",
        descripcionIngles: "A relative of raccoons, recognized by its long tail and flexible snout. They commonly travel in noisy groups.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Nasua_narica.jpg?width=600"
    },
    {
        id: 14,
        nombreEspanol: "Víbora de pestañas",
        nombreIngles: "Eyelash viper",
        cientificoEspanol: "Bothriechis schlegelii",
        cientificoIngles: "Bothriechis schlegelii",
        categoria: "Reptiles",
        descripcionEspanol: "Serpiente venenosa arbórea de tamaño pequeño. Destaca por las escamas modificadas sobre sus ojos que parecen pestañas.",
        descripcionIngles: "A small, arboreal venomous snake known for modified scales above its eyes that resemble eyelashes.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Bothriechis_schlegelii.jpg?width=600"
    },
    {
        id: 15,
        nombreEspanol: "Rana de vidrio",
        nombreIngles: "Fleischmann's glass frog",
        cientificoEspanol: "Hyalinobatrachium fleischmanni",
        cientificoIngles: "Hyalinobatrachium fleischmanni",
        categoria: "Anfibios",
        descripcionEspanol: "Llamada así porque la piel de su vientre es translúcida, permitiendo ver sus órganos internos y su corazón en funcionamiento.",
        descripcionIngles: "Named for its translucent belly skin, which allows a view of its internal organs and beating heart.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Hyalinobatrachium_fleischmanni.jpg?width=600"
    },
    {
        id: 16,
        nombreEspanol: "Saíno / Pecarí",
        nombreIngles: "Collared peccary",
        cientificoEspanol: "Pecari tajacu",
        cientificoIngles: "Pecari tajacu",
        categoria: "Mamíferos",
        descripcionEspanol: "Mamífero similar a un cerdo silvestre que vive en manadas. Tienen una glándula almizclera con la que marcan su territorio.",
        descripcionIngles: "A mammal resembling a wild pig that lives in herds. They have a musk gland used to mark their territory.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Collared_Peccary.jpg?width=600"
    },
    {
        id: 17,
        nombreEspanol: "Pelícano pardo",
        nombreIngles: "Brown pelican",
        cientificoEspanol: "Pelecanus occidentalis",
        cientificoIngles: "Pelecanus occidentalis",
        categoria: "Aves",
        descripcionEspanol: "Ave marina grande, común en las costas del Caribe y Pacífico. Caza lanzándose en picada espectacular desde el aire hacia el mar.",
        descripcionIngles: "A large seabird, common on both Caribbean and Pacific coasts. It hunts by dramatically plunge-diving from the air into the sea.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Pelecanus_occidentalis.jpg?width=600"
    },
    {
        id: 18,
        nombreEspanol: "Tortuga baula",
        nombreIngles: "Leatherback sea turtle",
        cientificoEspanol: "Dermochelys coriacea",
        cientificoIngles: "Dermochelys coriacea",
        categoria: "Reptiles",
        descripcionEspanol: "La tortuga marina más grande del planeta. No tiene un caparazón rígido, sino una piel coriácea similar al cuero.",
        descripcionIngles: "The largest marine turtle on the planet. It lacks a rigid shell, instead having a leathery, skin-like covering.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Dermochelys_coriacea.jpg?width=600"
    },
    {
        id: 19,
        nombreEspanol: "Mono carablanca",
        nombreIngles: "White-headed capuchin",
        cientificoEspanol: "Cebus imitator",
        cientificoIngles: "Cebus imitator",
        categoria: "Mamíferos",
        descripcionEspanol: "Altamente inteligente y sumamente activo. Es uno de los monos más comunes y reconocidos de los parques nacionales de Costa Rica.",
        descripcionIngles: "Highly intelligent and very active. It is one of the most common and recognized monkeys in Costa Rica's national parks.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Capuchin_Costa_Rica.jpg?width=600"
    },
    {
        id: 20,
        nombreEspanol: "Pájaro campana",
        nombreIngles: "Three-wattled bellbird",
        cientificoEspanol: "Procnias tricarunculatus",
        cientificoIngles: "Procnias tricarunculatus",
        categoria: "Aves",
        descripcionEspanol: "Famoso por su fuerte canto metálico similar al tañido de una campana y por las tres carúnculas largas que cuelgan de su pico.",
        descripcionIngles: "Famous for its loud, metallic call resembling the ring of a bell, and for the three long wattles hanging from its beak.",
        imagen: "https://upload.wikimedia.org/wikipedia/commons/8/80/Three-wattled_Bellbird_%28Procnias_tricarunculata%29_%285818992683%29.jpg"
    },
    {
        id: 21,
        nombreEspanol: "Boa constrictora",
        nombreIngles: "Boa constrictor",
        cientificoEspanol: "Boa constrictor",
        cientificoIngles: "Boa constrictor",
        categoria: "Reptiles",
        descripcionEspanol: "Serpiente grande y no venenosa que somete a sus presas mediante constricción. Es pacífica y habita en diversos climas.",
        descripcionIngles: "A large, non-venomous snake that subdues its prey through constriction. Peaceful and found in a wide range of climates.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Boa_constrictor.jpg?width=600"
    },
    {
        id: 22,
        nombreEspanol: "Rana toro",
        nombreIngles: "American bullfrog",
        cientificoEspanol: "Lithobates catesbeianus",
        cientificoIngles: "Lithobates catesbeianus",
        categoria: "Anfibios",
        descripcionEspanol: "Anfibio de gran tamaño con un canto grave y potente. Habita cuerpos de agua estancados o de corriente lenta.",
        descripcionIngles: "A large amphibian with a deep, powerful call. It inhabits stagnant or slow-moving bodies of water.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/North-American-bullfrog1.jpg?width=600"
    },
    {
        id: 24,
        nombreEspanol: "Basilisco esmeralda",
        nombreIngles: "Green basilisk",
        cientificoEspanol: "Basiliscus plumifrons",
        cientificoIngles: "Basiliscus plumifrons",
        categoria: "Reptiles",
        descripcionEspanol: "Conocido popularmente como 'Lagarto de Jesucristo' debido a su asombrosa habilidad para correr sobre la superficie del agua sin hundirse.",
        descripcionIngles: "Popularly known as the 'Jesus Christ Lizard' for its remarkable ability to run across the surface of water without sinking.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Basiliscus_plumifrons.jpg?width=600"
    },
    {
        id: 25,
        nombreEspanol: "Ocelote / Manigordo",
        nombreIngles: "Ocelot",
        cientificoEspanol: "Leopardus pardalis",
        cientificoIngles: "Leopardus pardalis",
        categoria: "Mamíferos",
        descripcionEspanol: "Felino de tamaño mediano con manchas hermosas en forma de rosetas. Se le llama manigordo por el gran tamaño relativo de sus patas delanteras.",
        descripcionIngles: "A medium-sized feline with beautiful rosette-shaped markings. Called 'manigordo' locally for the relatively large size of its front paws.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Leopardus_pardalis.jpg?width=600"
    },
    {
        id: 26,
        nombreEspanol: "Lapa azul y amarilla",
        nombreIngles: "Blue-and-yellow macaw",
        cientificoEspanol: "Ara ararauna",
        cientificoIngles: "Ara ararauna",
        categoria: "Aves",
        descripcionEspanol: "Gran guacamayo de color azul brillante en el lomo y amarillo intenso en el pecho. Es un ave sumamente sociable e inteligente.",
        descripcionIngles: "A large macaw with brilliant blue upperparts and intense yellow underparts. Highly sociable and intelligent.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Ara_ararauna.jpg?width=600"
    },
    {
        id: 27,
        nombreEspanol: "Rana dardo verde y negra",
        nombreIngles: "Green-and-black poison frog",
        cientificoEspanol: "Dendrobates auratus",
        cientificoIngles: "Dendrobates auratus",
        categoria: "Anfibios",
        descripcionEspanol: "Anfibio pequeño con un patrón llamativo de manchas verdes y negras. Habita en la hojarasca de los bosques lluviosos del Caribe.",
        descripcionIngles: "A small amphibian with striking green and black markings. It inhabits the leaf litter of Caribbean rainforests.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Dendrobates_auratus.jpg?width=600"
    },
    {
        id: 28,
        nombreEspanol: "Iguana verde",
        nombreIngles: "Green iguana",
        cientificoEspanol: "Iguana iguana",
        cientificoIngles: "Iguana iguana",
        categoria: "Reptiles",
        descripcionEspanol: "Uno de los reptiles arbóreos más grandes del país. Pasan la mayor parte del tiempo en las ramas altas de árboles cercanos a ríos.",
        descripcionIngles: "One of the largest arboreal reptiles in the country. It spends most of its time in high branches near rivers.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Iguana_iguana.jpg?width=600"
    },
    {
        id: 29,
        nombreEspanol: "Mono tití",
        nombreIngles: "Central American squirrel monkey",
        cientificoEspanol: "Saimiri oerstedii",
        cientificoIngles: "Saimiri oerstedii",
        categoria: "Mamíferos",
        descripcionEspanol: "El mono más pequeño de Costa Rica. Se encuentra en peligro de extinción y su hábitat principal se limita al Parque Nacional Manuel Antonio.",
        descripcionIngles: "The smallest monkey in Costa Rica. It is endangered, with its main habitat limited to Manuel Antonio National Park.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Black-crowned_Central_American_squirrel_monkey,_Saimiri_oerstedii_oerstedii.jpg?width=600"
    },
    {
        id: 30,
        nombreEspanol: "Fragata magnífica",
        nombreIngles: "Magnificent frigatebird",
        cientificoEspanol: "Fregata magnificens",
        cientificoIngles: "Fregata magnificens",
        categoria: "Aves",
        descripcionEspanol: "Ave marina de enormes alas. Los machos poseen un saco gular rojo brillante en el pecho que inflan como un globo durante el cortejo.",
        descripcionIngles: "A seabird with enormous wings. Males display a brilliant red throat pouch that they inflate like a balloon during courtship.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Magnificent_Frigatebird.jpg?width=600"
    },
    {
        id: 31,
        nombreEspanol: "Serpiente terciopelo",
        nombreIngles: "Fer-de-lance",
        cientificoEspanol: "Bothrops asper",
        cientificoIngles: "Bothrops asper",
        categoria: "Reptiles",
        descripcionEspanol: "La serpiente venenosa más famosa e imponente del país. Es de gran tamaño, terrestre y posee un patrón geométrico de camuflaje en X.",
        descripcionIngles: "The most famous and imposing venomous snake in the country. Large and terrestrial, with a geometric X-pattern for camouflage.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Bothrops_asper.jpg?width=600"
    },
    {
        id: 32,
        nombreEspanol: "Sapo común / Sapo de caña",
        nombreIngles: "Cane toad",
        cientificoEspanol: "Rhinella marina",
        cientificoIngles: "Rhinella marina",
        categoria: "Anfibios",
        descripcionEspanol: "Un sapo terrestre de gran tamaño. Posee glándulas parotoides detrás de sus ojos que secretan una toxina blanca cuando se siente amenazado.",
        descripcionIngles: "A large terrestrial toad. It has parotoid glands behind its eyes that secrete a white toxin when threatened.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Rhinella_marina.jpg?width=600"
    },
    {
        id: 33,
        nombreEspanol: "Puma",
        nombreIngles: "Cougar / Puma",
        cientificoEspanol: "Puma concolor",
        cientificoIngles: "Puma concolor",
        categoria: "Mamíferos",
        descripcionEspanol: "El segundo felino más grande de Costa Rica. Tiene una gran capacidad de adaptación y habita desde bosques secos hasta montañas altas.",
        descripcionIngles: "The second largest feline in Costa Rica. Highly adaptable, it inhabits environments ranging from dry forests to high mountains.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Puma_concolor.jpg?width=600"
    },
    {
        id: 34,
        nombreEspanol: "Momoto corona azul",
        nombreIngles: "Blue-capped motmot",
        cientificoEspanol: "Momotus coeruliceps",
        cientificoIngles: "Momotus coeruliceps",
        categoria: "Aves",
        descripcionEspanol: "Ave conocida por su corona azul brillante y su cola larga con terminaciones en forma de raqueta que mueve como un péndulo.",
        descripcionIngles: "A bird known for its brilliant blue crown and long racket-tipped tail feathers, which it swings like a pendulum.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Blue-crowned_Motmot.jpg?width=600"
    },
    {
        id: 35,
        nombreEspanol: "Tortuga carey",
        nombreIngles: "Hawksbill sea turtle",
        cientificoEspanol: "Eretmochelys imbricata",
        cientificoIngles: "Eretmochelys imbricata",
        categoria: "Reptiles",
        descripcionEspanol: "Tortuga marina críticamente amenazada. Su caparazón tiene placas superpuestas con colores llamativos y su boca semeja el pico de un halcón.",
        descripcionIngles: "A critically endangered sea turtle. Its shell has overlapping plates with vivid colors, and its beak resembles a hawk's.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Eretmochelys_imbricata.jpg?width=600"
    },
    {
        id: 36,
        nombreEspanol: "Rana arborícola de hocico redondo",
        nombreIngles: "Mexican tree frog",
        cientificoEspanol: "Smilisca baudinii",
        cientificoIngles: "Smilisca baudinii",
        categoria: "Anfibios",
        descripcionEspanol: "Rana nocturna arbórea común en zonas bajas y húmedas. Posee la capacidad de cambiar su coloración de marrón a verde claro rápidamente.",
        descripcionIngles: "A common nocturnal tree frog found in low, humid areas. It can quickly change its color from brown to light green.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Smilisca_baudinii.jpg?width=600"
    },
    {
        id: 37,
        nombreEspanol: "Tamandúa / Oso hormiguero",
        nombreIngles: "Northern tamandua",
        cientificoEspanol: "Tamandua mexicana",
        cientificoIngles: "Tamandua mexicana",
        categoria: "Mamíferos",
        descripcionEspanol: "Oso hormiguero mediano arbóreo. Destaca por su pelaje que parece un chaleco negro sobre un fondo beige y su cola prensil.",
        descripcionIngles: "A medium-sized arboreal anteater, recognized by its fur that looks like a black vest over a beige background and its prehensile tail.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Tamandua_mexicana.jpg?width=600"
    },
    {
        id: 38,
        nombreEspanol: "Zopilote rey",
        nombreIngles: "King vulture",
        cientificoEspanol: "Sarcoramphus papa",
        cientificoIngles: "Sarcoramphus papa",
        categoria: "Aves",
        descripcionEspanol: "El ave carroñera más grande y vistosa del país. Su plumaje es principalmente blanco y negro, con una cabeza llena de colores intensos.",
        descripcionIngles: "The largest and most colorful scavenger in the country. Its plumage is primarily black and white, with a brightly colored head.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Sarcoramphus_papa.jpg?width=600"
    },
    {
        id: 39,
        nombreEspanol: "Serpiente coral",
        nombreIngles: "Central American coral snake",
        cientificoEspanol: "Micrurus nigrocinctus",
        cientificoIngles: "Micrurus nigrocinctus",
        categoria: "Reptiles",
        descripcionEspanol: "Serpiente pequeña sumamente venenosa, con anillos brillantes y definidos en un patrón de color rojo, amarillo y negro.",
        descripcionIngles: "A small, highly venomous snake with bright, well-defined rings in a red, yellow, and black pattern.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Coral_snake.jpg?width=600"
    },
    {
        id: 40,
        nombreEspanol: "Rana de hojarasca",
        nombreIngles: "Fitzinger's rain frog",
        cientificoEspanol: "Craugastor fitzingeri",
        cientificoIngles: "Craugastor fitzingeri",
        categoria: "Anfibios",
        descripcionEspanol: "Pequeña rana terrestre de color marrón que se camufla perfectamente con las hojas secas del suelo del bosque. Su desarrollo es directo.",
        descripcionIngles: "A small, brown terrestrial frog that camouflages perfectly with dry forest floor leaves. It has direct development, with no tadpole stage.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Craugastor_fitzingeri.jpg?width=600"
    },
    {
        id: 42,
        nombreEspanol: "Gavilán pollero",
        nombreIngles: "Roadside hawk",
        cientificoEspanol: "Rupornis magnirostris",
        cientificoIngles: "Rupornis magnirostris",
        categoria: "Aves",
        descripcionEspanol: "Una de las aves de presa más comunes de observar posada en postes de luz o ramas bajas a lo largo de las carreteras del país.",
        descripcionIngles: "One of the most commonly seen birds of prey, often perched on utility poles or low branches along the country's roads.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Buteo_magnirostris.jpg?width=600"
    },
    {
        id: 43,
        nombreEspanol: "Gecko casero",
        nombreIngles: "Common house gecko",
        cientificoEspanol: "Hemidactylus frenatus",
        cientificoIngles: "Hemidactylus frenatus",
        categoria: "Reptiles",
        descripcionEspanol: "Pequeño lagarto nocturno muy común en las paredes de las casas. Es un excelente controlador biológico de mosquitos e insectos.",
        descripcionIngles: "A small nocturnal lizard very common on house walls. An excellent biological controller of mosquitoes and insects.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Hemidactylus_frenatus.jpg?width=600"
    },
    {
        id: 44,
        nombreEspanol: "Sapo de Campbell",
        nombreIngles: "Campbell's rainforest toad",
        cientificoEspanol: "Rhinella campbelli",
        cientificoIngles: "Rhinella campbelli",
        categoria: "Anfibios",
        descripcionEspanol: "Sapo pequeño que vive entre la hojarasca densa del bosque. Su cuerpo plano imita a la perfección una hoja seca en descomposición.",
        descripcionIngles: "A small toad that lives in dense forest leaf litter. Its flat body perfectly imitates a decomposing dry leaf.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Bufo_marinus.jpg?width=600"
    },
    {
        id: 45,
        nombreEspanol: "Zorro pelón / Tlacuache",
        nombreIngles: "Virginia opossum",
        cientificoEspanol: "Didelphis virginiana",
        cientificoIngles: "Didelphis virginiana",
        categoria: "Mamíferos",
        descripcionEspanol: "Un marsupial nocturno y omnívoro sumamente adaptable. Las hembras cargan a sus crías dentro de una bolsa llamada marsupio.",
        descripcionIngles: "A nocturnal, omnivorous marsupial that is highly adaptable. Females carry their young inside a pouch called a marsupium.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Didelphis_virginiana.jpg?width=600"
    },
    {
        id: 46,
        nombreEspanol: "Caracara común",
        nombreIngles: "Crested caracara",
        cientificoEspanol: "Caracara plancus",
        cientificoIngles: "Caracara plancus",
        categoria: "Aves",
        descripcionEspanol: "Ave de presa grande de la familia de los falcónidos. Camina con facilidad en el suelo buscando carroña o pequeños animales.",
        descripcionIngles: "A large bird of prey from the falcon family. It walks easily on the ground, searching for carrion or small animals.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Caracara_plancus.jpg?width=600"
    },
    {
        id: 47,
        nombreEspanol: "Caimán de anteojos",
        nombreIngles: "Spectacled caiman",
        cientificoEspanol: "Caiman crocodilus",
        cientificoIngles: "Caiman crocodilus",
        categoria: "Reptiles",
        descripcionEspanol: "Reptil similar al cocodrilo pero de menor tamaño. Se le llama 'de anteojos' debido a una protuberancia ósea que une sus ojos.",
        descripcionIngles: "A reptile similar to a crocodile but smaller. Called 'spectacled' due to a bony ridge connecting its eyes.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Spectacled_Caiman.JPG?width=600"
    },
    {
        id: 48,
        nombreEspanol: "Rana arborícola de bandas doradas",
        nombreIngles: "Golden-grooved tree frog",
        cientificoEspanol: "Smilisca sordida",
        cientificoIngles: "Smilisca sordida",
        categoria: "Anfibios",
        descripcionEspanol: "Pequeña rana que habita cerca de riachuelos de corriente rápida en zonas montañosas. Los machos cantan sobre las rocas húmedas.",
        descripcionIngles: "A small frog found near fast-moving streams in mountain areas. Males call from wet rocks.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Smilisca_sordida.jpg?width=600"
    },
    {
        id: 49,
        nombreEspanol: "Jaguarundi",
        nombreIngles: "Jaguarundi",
        cientificoEspanol: "Herpailurus yagouaroundi",
        cientificoIngles: "Herpailurus yagouaroundi",
        categoria: "Mamíferos",
        descripcionEspanol: "Un felino pequeño de cuerpo alargado y patas cortas, similar a una nutria o comadreja. Es de hábitos principalmente diurnos.",
        descripcionIngles: "A small feline with an elongated body and short legs, resembling an otter or weasel. Mainly active during the day.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/Jaguarundi.jpg?width=600"
    },
    {
        id: 50,
        nombreEspanol: "Pelícano blanco americano",
        nombreIngles: "American white pelican",
        cientificoEspanol: "Pelecanus erythrorhynchos",
        cientificoIngles: "Pelecanus erythrorhynchos",
        categoria: "Aves",
        descripcionEspanol: "Ave migratoria gigante que llega a los humedales de Costa Rica durante el invierno del norte. Cazan en grupos coordinados.",
        descripcionIngles: "A giant migratory bird that visits Costa Rica's wetlands during the northern winter. They hunt cooperatively in coordinated groups.",
        imagen: "https://commons.wikimedia.org/wiki/Special:FilePath/American_White_Pelican.jpg?width=600"
    }
];
